name: vendingmachineapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  permission_handler: ^5.0.1+1
  qrscan: ^0.2.19
  flutter_vlc_player: ^1.0.0
  http: ^0.12.0+4
  material_design_icons_flutter: ^4.0.5655
  path_provider: ^1.6.24

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/LOGO3.png

flutter_icons:
  image_path: 'images/LOGO3.png'
  android: true
  ios: true
